version: '3'
services:
  proxy:
    image: nginx:latest
    container_name: proxy
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./client/build:/usr/share/nginx/html
    restart: "always"

  express:
    build:
      context: ./server
    container_name: express
    expose:
      - "3000"
    # expose와 ports의 차이는 무엇인가?
    volumes:
      - ./server/:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    restart: "always"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongodb_volume:/data/db
    ports:
      - "27017:27017"
    restart: "always"

volumes:
  mongodb_volume:
